name: Cypress Tests
on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node v4
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npx --node-options="--require=tsx" cypress run --reporter mochawesome --reporter-options 'reportDir=cypress/results,overwrite=false,html=false,json=true'
      - name: Merge test results
        run: npx mochawesome-merge "cypress/results/*.json" > cypress/results/output.json
      - name: Generate HTML report
        run: npx mochawesome-report-generator cypress/results/output.json
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 7
